import type { Movie } from "@/api/entities/movies/types";

/**
 * Mock movies data for grid calculation
 * Used to measure grid dimensions without loading from localStorage
 */
export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Mock Movie 1",
    overview: "This is a mock movie description for movie 1",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 1",
  },
  {
    id: 2,
    title: "Mock Movie 2",
    overview: "This is a mock movie description for movie 2",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 2",
  },
  {
    id: 3,
    title: "Mock Movie 3",
    overview: "This is a mock movie description for movie 3",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 3",
  },
  {
    id: 4,
    title: "Mock Movie 4",
    overview: "This is a mock movie description for movie 4",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 4",
  },
  {
    id: 5,
    title: "Mock Movie 5",
    overview: "This is a mock movie description for movie 5",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 5",
  },
  {
    id: 6,
    title: "Mock Movie 6",
    overview: "This is a mock movie description for movie 6",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 6",
  },
  {
    id: 7,
    title: "Mock Movie 7",
    overview: "This is a mock movie description for movie 7",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 7",
  },
  {
    id: 8,
    title: "Mock Movie 8",
    overview: "This is a mock movie description for movie 8",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 8",
  },
  {
    id: 9,
    title: "Mock Movie 9",
    overview: "This is a mock movie description for movie 9",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 9",
  },
  {
    id: 10,
    title: "Mock Movie 10",
    overview: "This is a mock movie description for movie 10",
    poster_path: null,
    backdrop_path: null,
    release_date: "2024-01-01",
    vote_average: 7.5,
    vote_count: 1000,
    popularity: 50.0,
    genre_ids: [1, 2, 3],
    adult: false,
    original_language: "en",
    original_title: "Mock Movie 10",
  },
];
